spring.application.name=machado-bank

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS SEGURA (CON VARIABLES DE ENTORNO)
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:bu4tvw79pswewlrao6hb-mysql.services.clever-cloud.com}:${DB_PORT:3306}/${DB_NAME:bu4tvw79pswewlrao6hb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:uqemimu3xlphxv0d}
spring.datasource.password=${DB_PASSWORD:4320xaX99pYMZH2OTuUC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Se mantienen propiedades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false